apiVersion: v2
name: umpp
description: UMPP control plane, dashboard, and optional development dependencies
type: application
version: 0.1.0
appVersion: "v1-r2"
kubeVersion: ">=1.25.0-0"
keywords:
  - umpp
  - networking
  - wireguard
maintainers:
  - name: UMPP
