BEGIN;
ALTER TABLE proxy_rules ADD COLUMN IF NOT EXISTS upstream_scheme VARCHAR(16) NOT NULL DEFAULT 'http';
ALTER TABLE proxy_rules ADD COLUMN IF NOT EXISTS upstream_insecure_skip_verify BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE proxy_rules ADD COLUMN IF NOT EXISTS upstream_ca_file VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE virtual_networks ADD COLUMN IF NOT EXISTS preshared_key TEXT NOT NULL DEFAULT '';
COMMIT;
