BEGIN;

ALTER TABLE certificates ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'active';
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS last_error TEXT NOT NULL DEFAULT '';
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS renewed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS renew_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS challenge_type VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS renewal_failures INTEGER NOT NULL DEFAULT 0;
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_certificates_status ON certificates (status);
CREATE INDEX IF NOT EXISTS idx_certificates_expires_at ON certificates (expires_at);
CREATE INDEX IF NOT EXISTS idx_certificates_created_at ON certificates (created_at);

COMMIT;
