apiVersion: v2
name: neilico
description: NEILICO control plane, dashboard, and optional development dependencies
type: application
version: 0.1.0
appVersion: "v1-r2"
kubeVersion: ">=1.25.0-0"
keywords:
  - neilico
  - networking
  - wireguard
maintainers:
  - name: NEILICO
