{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "umpp.serviceAccountName" . }}
  labels:
    {{- include "umpp.componentLabels" (dict "root" . "component" "service-account") | nindent 4 }}
  annotations:
    {{- include "umpp.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
