{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "neilico.fullname" . }}
  labels:
    {{- include "neilico.componentLabels" (dict "root" . "component" "ingress") | nindent 4 }}
  annotations:
    {{- include "neilico.annotations" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq .service "controlApi" }}
                name: {{ include "neilico.controlApi.fullname" $ }}
                port:
                  name: api
                {{- else }}
                name: {{ include "neilico.dashboard.fullname" $ }}
                port:
                  name: http
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
